# Vietoris-Rips filtration
In this notebook there is the application Giotto TDA Vietoris Rips filtration computation on random graphs and on the come dataset

## Random Graphs
We apply the Vietoris Rips filtration to Erdos-Renyi, Watts-Strogatz and ring lattice graphs 

In [1]:
from HomologyPackage.NetworkGeneration import Erdos_Renyi, Watts_Strogatz, ring_lattice
from HomologyPackage import normalize
import numpy as np

Let us generate some random graph with 90 nodes in order to be consistent with the number of nodes in the coma dataset

In [2]:
seed = 0
er = Erdos_Renyi(90,seed=seed)
ws01 = Watts_Strogatz(90,0.01,seed=seed)
ws1 = Watts_Strogatz(90,0.1,seed=seed)
ws5 = Watts_Strogatz(90,0.5,seed=seed)
rl= ring_lattice(90,seed=seed)
er

array([[0.        , 0.63696169, 0.26978671, ..., 0.71114288, 0.93205969,
        0.11493263],
       [0.63696169, 0.        , 0.72901512, ..., 0.88009812, 0.8123354 ,
        0.66788941],
       [0.26978671, 0.72901512, 0.        , ..., 0.32228672, 0.79663918,
        0.22532844],
       ...,
       [0.71114288, 0.88009812, 0.32228672, ..., 0.        , 0.45906189,
        0.86911055],
       [0.93205969, 0.8123354 , 0.79663918, ..., 0.45906189, 0.        ,
        0.80248291],
       [0.11493263, 0.66788941, 0.22532844, ..., 0.86911055, 0.80248291,
        0.        ]])

Giotto TDA requires a distance matrix, therefore we need to do some preprocessing

In [3]:
def preprocess(l):
    net_list=[]
    for net in l:
        net=np.abs(net)
        #net=normalize(net)
        net=1-net
        np.fill_diagonal(net,0)
        net_list.append(net)
    return net_list

net_list=preprocess([er,ws5,ws1,ws01,rl])

In [6]:
from gtda.homology import VietorisRipsPersistence
VR = VietorisRipsPersistence(metric="precomputed",homology_dimensions=[0,1,2])
diagrams = VR.fit_transform(net_list)

In [11]:
VR.plot(diagrams, sample=0)

### Betti Curves
We want now to plot some betti curves of the previous persistence diagrams

In [13]:
from gtda.diagrams import BettiCurve

BC=BettiCurve(n_bins=100)

BC.fit_transform_plot(diagrams,sample=0)
#BC.samplings_
#print(diagrams[diagrams[:,3]==1])
#d=diagrams[4]
#max(d[:,1])

array([[[ 89,  86,  85,  81,  79,  79,  77,  72,  70,  69,  66,  61,
          60,  60,  59,  58,  55,  51,  50,  48,  47,  46,  43,  41,
          40,  39,  36,  35,  34,  33,  33,  30,  30,  29,  28,  26,
          25,  23,  21,  21,  21,  19,  19,  19,  19,  18,  16,  16,
          15,  15,  15,  15,  15,  15,  15,  14,  13,  12,  11,  10,
          10,   9,   7,   7,   7,   7,   7,   6,   6,   6,   6,   6,
           5,   5,   5,   5,   5,   5,   5,   5,   5,   5,   5,   5,
           5,   5,   5,   5,   4,   3,   3,   3,   3,   1,   1,   1,
           1,   1,   1,   0],
        [  1,  17,  34,  58,  75,  86, 105, 117, 135, 149, 158, 174,
         178, 184, 195, 195, 202, 205, 203, 197, 187, 179, 167, 135,
         109,  76,  53,  39,  30,  27,  20,  17,  11,  10,   9,   7,
           5,   2,   1,   1,   1,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
    

## Coma dataset
Let us repeat the same analysis on the Coma Dataset

In [14]:
import os

path="regional-differentiation-based-on-graph-nodal-statistics-for-functional-brain-connectivity-networks-characterization/DATA/cor_mat_coma"
files=os.listdir(path) #make a list of all the files' names at the path 

Let divide control from comatose individuals

In [15]:
patient_files = []
control_files = []
for file in files:
    if 'Patient' in file:
        patient_files.append(file)
    else:
        control_files.append(file)
        
patients = [np.loadtxt(path+"/"+file, usecols=range(1,91), skiprows=1, dtype='float') for file in patient_files]
controls = [np.loadtxt(path+"/"+file, usecols=range(1,91), skiprows=1, dtype='float') for file in control_files]

It is again necessary to preprocess data

In [16]:
patients_preprocessed= preprocess(patients)
controls_preprocessed= preprocess(controls)

In [17]:
VR = VietorisRipsPersistence(metric="precomputed",homology_dimensions=[0,1,2])
dms_patients = VR.fit_transform(patients_preprocessed)

In [18]:
dms_controls = VR.fit_transform(controls_preprocessed)

In [26]:
#sample 0-15
sample=0
VR.plot(dms_patients, sample=sample)

In [27]:
BC.fit_transform_plot(dms_patients,sample=sample)

array([[[89, 89, 88, 88, 82, 80, 76, 69, 58, 54, 49, 36, 31, 27, 24, 24,
         20, 19, 16, 15, 13, 11, 11, 11, 11,  8,  7,  7,  6,  5,  5,  4,
          4,  4,  4,  3,  3,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
          2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
          1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0],
        [ 0,  0,  0,  1,  1,  2,  2,  1,  0,  3,  2,  5,  5,  5,  5,  2,
          1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,

In [25]:
#sample 0-19
sample=13
VR.plot(dms_controls, sample=sample)

In [28]:
BC.fit_transform_plot(dms_controls,sample=sample)

array([[[89, 89, 89, 89, 89, 88, 88, 87, 87, 86, 84, 82, 81, 78, 77, 76,
         73, 70, 67, 63, 59, 56, 55, 54, 50, 49, 45, 43, 42, 42, 41, 39,
         39, 36, 32, 30, 28, 27, 26, 21, 20, 18, 18, 18, 17, 17, 17, 16,
         16, 14, 12, 12, 12, 11, 10, 10, 10, 10, 10,  9,  7,  6,  3,  3,
          3,  2,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  2,
          1,  0,  0,  0,  1,  1,  3,  2,  3,  3,  3,  2,  2,  4,  4,  3,
          3,  5,  9,  7,  9, 11, 13, 13, 12, 11,  9,  9,  9,  7,  5,  5,
          3,  2,  3,  3,  4,  4,  3,  3,  3,  5,  4,  2,  4,  2,  2,  2,
          2,  1,  1,  2,  3,  4,  5,  4,  4,  4,  5,  5,  4,  2,  4,  2,
          2,  2,  2,  2,  2,  2,  1,  2,  2,  2,  1,  1,  3,  2,  2,  1,
          1,  1,  1,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,

Now let us save the betti's numbers of both patients and controls on a file

In [117]:
VR = VietorisRipsPersistence(metric="precomputed",homology_dimensions=[0,1,2])
dms = VR.fit_transform(patients_preprocessed+controls_preprocessed)
betti_controls=[]
betti_patients=[]
for sample in range(len(patients_preprocessed+controls_preprocessed)):
    if sample<16:
        betti_patients.append(BC.fit_transform_plot(dms,sample=sample))
    else:
        betti_controls.append(BC.fit_transform_plot(dms,sample=sample))


[array([[[89, 89, 88, 88, 82, 80, 76, 69, 58, 54, 49, 36, 31, 27, 24, 24,
          20, 19, 16, 15, 13, 11, 11, 11, 11,  8,  7,  7,  6,  5,  5,  4,
           4,  4,  4,  3,  3,  3,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
           2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
           1,  1,  1,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  0],
         [ 0,  0,  0,  0,  1,  2,  2,  2,  0,  2,  3,  3,  5,  5,  5,  3,
           1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0,  0,  0],
         [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0, 

In [119]:
import pickle

with open('data/patients_betti', "wb") as f:
    pickle.dump((betti_patients,patient_files,BC.samplings_), f, protocol=pickle.HIGHEST_PROTOCOL)
    
with open('data/controls_betti', "wb") as f:
    pickle.dump((betti_controls,control_files,BC.samplings_), f, protocol=pickle.HIGHEST_PROTOCOL)